# API Configuration
api_collector:
  api_key: "${UN_API_KEY}"  # Usa variabile d'ambiente
  base_url: "https://api.un.org"
  endpoints:
    missions:
      path: "peacekeeping/missions"
      params:
        limit: 100
        format: "json"
      data_path: "data"
    countries:
      path: "countries"
      params:
        format: "json"
      data_path: "data"
    peacekeeping:
      path: "peacekeeping/operations"
      params:
        format: "json"
      data_path: "data"
  required_columns:
    - "id"
    - "name"
    - "date"
    - "location"
    - "status"
    - "type"
    - "mandate"
    - "troop_count"
    - "budget"

# Web Scraping Configuration
web_scraper:
  urls:
    - "https://peacekeeping.un.org/en/where-we-operate"
    - "https://peacekeeping.un.org/en/mission"
    - "https://peacekeeping.un.org/en/our-peacekeeping-missions"
  selectors:
    mission_list:
      css: "div.views-row, div.mission-item, div.mission-card"
      fields:
        title:
          type: "text"
          css: "h2.field-content, h3.mission-title, h2.mission-name"
        description:
          type: "text"
          css: "div.field-content, div.mission-description, p.mission-summary"
        date:
          type: "text"
          css: "span.date-display-single, span.mission-date, time.mission-period"
        link:
          type: "attribute"
          css: "a"
          attr: "href"
        location:
          type: "text"
          css: "div.field-location, span.mission-location, div.mission-country"
        status:
          type: "text"
          css: "div.field-status, span.mission-status, div.mission-state"
  delay: 2
  required_columns:
    - "title"
    - "description"
    - "date"
    - "location"
    - "status"

# RSS Feed Configuration
rss_collector:
  feeds:
    - "https://peacekeeping.un.org/en/feed"
    - "https://news.un.org/en/feed"
  delay: 1
  required_columns:
    - "title"
    - "link"
    - "published"

# OCR Configuration
ocr_collector:
  input_path: "data/documents"
  output_path: "data/processed/ocr"
  poppler_path: "C:/Program Files/poppler-24.02.0/Library/bin"  # Percorso di installazione di Poppler
  tesseract_cmd: "C:/Program Files/Tesseract-OCR/tesseract.exe"  # Percorso di Tesseract OCR
  languages: ["ita", "eng"]  # Lingue per il riconoscimento del testo
  required_columns:
    - "filename"
    - "text"
    - "processed_date"
    - "page_number"
    - "confidence"

# Social Media Configuration
social_media_collector:
  platform: "twitter"
  api_keys:
    bearer_token: "YOUR_BEARER_TOKEN_HERE"
    api_key: "YOUR_API_KEY_HERE"
    api_secret: "YOUR_API_SECRET_HERE"
    access_token: "YOUR_ACCESS_TOKEN_HERE"
    access_token_secret: "YOUR_ACCESS_TOKEN_SECRET_HERE"
  search_terms:
    - "peacekeeping mission"
    - "UN mission"
    - "international peace"
    - "peace operations"
    - "peacekeeping force"
    - "UN peacekeepers"
    - "peace mission"
    - "international security"
  max_results: 1000
  required_columns:
    - "text"
    - "created_at"
    - "id"
    - "user_id"
    - "retweet_count"
    - "favorite_count"
    - "hashtags"
    - "mentions"

# Database Configuration
database_collector:
  databases:
    un_missions:
      type: "csv"
      url: "https://data.un.org/ws/rest/data/DF_UNData_UNFCC"
      encoding: "utf-8"
    world_bank:
      type: "excel"
      url: "https://api.worldbank.org/v2/en/indicator/NY.GDP.MKTP.CD?downloadformat=excel"
      sheet_name: "Data"
    oecd:
      type: "csv"
      url: "https://stats.oecd.org/SDMX-JSON/data/AID_CRS/1.20001.1.1000.D/all?startTime=2020&endTime=2024"
      encoding: "utf-8"
    peacekeeping:
      type: "json"
      url: "https://peacekeeping.un.org/en/where-we-operate"
      format: "json"
    sipri:
      type: "csv"
      url: "https://www.sipri.org/sites/default/files/2024-01/sipri-military-expenditure-database-1949-2023.csv"
      encoding: "utf-8"
    ucdp:
      type: "csv"
      url: "https://ucdp.uu.se/downloads/ged/ged231-csv.zip"
      file_type: "csv"
  output_path: "data/processed/databases"
  required_columns:
    - "id"
    - "name"
    - "date"
    - "location"
    - "status"

# Document Collector Configuration
document_collector:
  urls:
    - "https://www.difesa.it/OperazioniMilitari/Pagine/default.aspx"
    - "https://www.esteri.it/it/politica_estera_e_cooperazione_internazionale/cooperazione_internazionale/"
    - "https://www.senato.it/leg/19/BGT/Schede/v3/Statistiche/v3StatisticheDettaglio.html"
    - "https://www.camera.it/leg19/1264"
    - "https://www.governo.it/it/articolo/missioni-internazionali"
    - "https://www.carabinieri.it/cittadino/informazioni/missioni-estero"
    - "https://www.marina.difesa.it/noi-siamo-la-marina/mezzi/forze-navali/Pagine/default.aspx"
    - "https://www.esercito.difesa.it/organizzazione/capo-di-sme/Comando-Forze-Operative-Sud/brigata-meccanizzata-aosta/Pagine/default.aspx"
    - "https://www.aeronautica.difesa.it/operazioni/Pagine/default.aspx"
  output_path: "data/documents"
  allowed_extensions:
    - ".pdf"
    - ".doc"
    - ".docx"
  allowed_domains:
    - "difesa.it"
    - "esteri.it"
    - "senato.it"
    - "camera.it"
    - "governo.it"
    - "carabinieri.it"
    - "marina.difesa.it"
    - "esercito.difesa.it"
    - "aeronautica.difesa.it"
  required_columns:
    - "filename"
    - "original_url"
    - "download_date"
    - "file_size"
    - "source_domain" 