# API Configuration
api_collector:
  api_key: "YOUR_API_KEY"
  base_url: "https://api.example.com"
  endpoints:
    missions:
      path: "missions"
      params:
        limit: 100
      data_path: "data.missions"
    countries:
      path: "countries"
      data_path: "data.countries"
  required_columns:
    - "id"
    - "name"
    - "date"

# Web Scraping Configuration
web_scraper:
  urls:
    - "https://peacekeeping.un.org/en/current-peacekeeping-operations"
    - "https://peacekeeping.un.org/en/past-peacekeeping-operations"
  selectors:
    mission_list:
      css: "div.views-row"
      fields:
        title:
          type: "text"
          css: "h2.field-content"
        description:
          type: "text"
          css: "div.field-content"
        date:
          type: "text"
          css: "span.date-display-single"
        link:
          type: "attribute"
          css: "a"
          attr: "href"
  delay: 2
  required_columns:
    - "title"
    - "description"
    - "date"

# RSS Feed Configuration
rss_collector:
  feeds:
    - "https://peacekeeping.un.org/en/feed"
    - "https://news.un.org/en/feed"
  delay: 1
  required_columns:
    - "title"
    - "link"
    - "published"

# OCR Configuration
ocr_collector:
  input_path: "data/documents"
  output_path: "data/processed/ocr"
  poppler_path: "C:/Program Files/poppler-24.02.0/Library/bin"  # Percorso di installazione di Poppler
  tesseract_cmd: "C:/Program Files/Tesseract-OCR/tesseract.exe"  # Percorso di Tesseract OCR
  languages: ["ita", "eng"]  # Lingue per il riconoscimento del testo
  required_columns:
    - "filename"
    - "text"
    - "processed_date"
    - "page_number"
    - "confidence"

# Social Media Configuration
social_media_collector:
  platform: "twitter"
  api_keys:
    bearer_token: "YOUR_BEARER_TOKEN_HERE"
    api_key: "YOUR_API_KEY_HERE"
    api_secret: "YOUR_API_SECRET_HERE"
    access_token: "YOUR_ACCESS_TOKEN_HERE"
    access_token_secret: "YOUR_ACCESS_TOKEN_SECRET_HERE"
  search_terms:
    - "peacekeeping mission"
    - "UN mission"
    - "international peace"
    - "peace operations"
    - "peacekeeping force"
    - "UN peacekeepers"
    - "peace mission"
    - "international security"
  max_results: 1000
  required_columns:
    - "text"
    - "created_at"
    - "id"
    - "user_id"
    - "retweet_count"
    - "favorite_count"
    - "hashtags"
    - "mentions"

# Database Configuration
database_collector:
  databases:
    un_missions:
      type: "csv"
      url: "https://data.humdata.org/dataset/peacekeeping-missions/resource/8c9c4c9a-4c9a-4c9a-4c9a-4c9a4c9a4c9a/download/peacekeeping-missions.csv"
      encoding: "utf-8"
    world_bank:
      type: "excel"
      url: "https://api.worldbank.org/v2/en/indicator/NY.GDP.MKTP.CD?downloadformat=excel"
      sheet_name: "Data"
    oecd:
      type: "csv"
      url: "https://stats.oecd.org/SDMX-JSON/data/AID_CRS/1.20001.1.1000.D/all?startTime=2020&endTime=2024"
      encoding: "utf-8"
    un_data:
      type: "json"
      url: "https://data.un.org/ws/rest/data/DF_UNData_UNFCC"
    peacekeeping:
      type: "zip"
      url: "https://peacekeeping.un.org/sites/default/files/peacekeeping-mission-data.zip"
      file_type: "csv"
  output_path: "data/processed/databases"
  required_columns:
    - "id"
    - "name"
    - "date" 