# Configurazione MIDA

# Percorsi delle directory
percorsi:
  data: "data"
  logs: "logs"
  reports: "reports"
  config: "config"
  raw_data: "data/raw"
  processed_data: "data/processed"

# Parametri per lo scraping
parametri_scraping:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  timeout: 60
  retry_attempts: 3
  retry_delay: 5
  delay_min: 1
  delay_max: 3

# Fonti dati
fonti_dati:
  camera_deputati:
    url_base: "https://www.camera.it"
    document_urls:
      - "https://www.camera.it/leg19/1134?shadow_primapagina=6553"
      - "https://www.camera.it/leg19/1134?shadow_primapagina=6554"
      - "https://www.camera.it/leg19/1134?shadow_primapagina=6555"
    sections:
      - "missioni-internazionali"
      - "documentazione"
  senato:
    url_base: "https://www.senato.it"
    document_urls:
      - "https://www.senato.it/leg/19/BGT/Schede/Dossier/Testi/00000001.htm"
      - "https://www.senato.it/leg/19/BGT/Schede/Dossier/Testi/00000002.htm"
    sections:
      - "missioni-internazionali"
      - "documentazione"
  difesa:
    url_base: "https://www.difesa.it"
    document_urls:
      - "https://www.difesa.it/OperazioniMilitari/Pagine/default.aspx"
      - "https://www.difesa.it/OperazioniMilitari/Documentazione/Pagine/default.aspx"
    sections:
      - "operazioni-militari"
      - "documentazione"
  esteri:
    url_base: "https://www.esteri.it"
    document_urls:
      - "https://www.esteri.it/mae/it/politica_estera/missioni_internazionali"
      - "https://www.esteri.it/mae/it/politica_estera/missioni_internazionali/documentazione"
    sections:
      - "missioni-internazionali"
      - "documentazione"
  eeas:
    url_base: "https://www.eeas.europa.eu"
    document_urls:
      - "https://www.eeas.europa.eu/eeas/missions-and-operations_en"
      - "https://www.eeas.europa.eu/eeas/civilian-missions-and-operations_en"
    sections:
      - "missions-and-operations"
      - "civilian-missions-and-operations"
  nato:
    url_base: "https://www.nato.int"
    document_urls:
      - "https://www.nato.int/cps/en/natohq/topics_52060.htm"
      - "https://www.nato.int/cps/en/natohq/topics_52061.htm"
    sections:
      - "operations-and-missions"
      - "current-operations"
  un:
    url_base: "https://peacekeeping.un.org"
    document_urls:
      - "https://peacekeeping.un.org/en/missions"
      - "https://peacekeeping.un.org/en/operations"
    sections:
      - "current-missions"
      - "past-missions"

# Configurazione logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/scraper_%Y%m%d.log"

# Configurazione proxy (opzionale)
proxy:
  enabled: false
  http: "http://proxy.example.com:8080"
  https: "https://proxy.example.com:8080"

# Configurazione email per le notifiche
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  from: "your-email@gmail.com"
  to: "recipient@example.com"

# Configurazione dashboard
dashboard:
  title: "MIDA - Dashboard Missioni Internazionali"
  description: "Monitoraggio e analisi delle missioni internazionali italiane"
  theme: "light"
  port: 8501

# Configurazione report
report:
  template: "scripts/reports/templates/report_template.html"
  output_dir: "reports"
  retention_days: 30

# Struttura dati
struttura_dati:
  colonne_obbligatorie:
    - nome_missione
    - paese
    - data_inizio
    - data_fine
    - personale_totale
    - costo_totale
    - tipo_missione
    - mandato
    - fonte
    - ultimo_aggiornamento
    - link_documento 