# Configurazione MIDA

# Percorsi delle directory
percorsi:
  data: "data"
  logs: "logs"
  reports: "reports"
  config: "config"

# Parametri per lo scraping
parametri_scraping:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  timeout: 60
  retry_attempts: 3
  retry_delay: 5
  request_delay: 5

# Fonti dati
fonti_dati:
  camera_deputati:
    url_base: "https://www.camera.it/leg18/1236"
    url_missioni: "https://www.camera.it/leg18/1236?tab=2&leg=18"
  senato:
    url_base: "https://www.senato.it/leg/18/BGT/Schede/Attivitainternazionali"
    url_missioni: "https://www.senato.it/leg/18/BGT/Schede/Attivitainternazionali/00000001.htm"
  difesa:
    url_base: "https://www.difesa.it/OperazioniMilitari"
    url_missioni: "https://www.difesa.it/OperazioniMilitari/Pagine/default.aspx"
  esteri:
    url_base: "https://www.esteri.it/mae/it/politica_estera"
    url_missioni: "https://www.esteri.it/mae/it/politica_estera/cooperazione_internazionale/missioni_internazionali"
  eeas:
    url_base: "https://eeas.europa.eu/headquarters/headquarters-homepage/area/geo_en"
    url_missioni: "https://eeas.europa.eu/headquarters/headquarters-homepage/area/geo_en"
  nato:
    url_base: "https://www.nato.int/cps/en/natohq/topics_52060.htm"
    url_missioni: "https://www.nato.int/cps/en/natohq/topics_52060.htm"
  un:
    url_base: "https://peacekeeping.un.org/en/missions"
    url_missioni: "https://peacekeeping.un.org/en/missions"

# Configurazione logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/scraper_%Y%m%d.log"

# Configurazione proxy (opzionale)
proxy:
  enabled: false
  http: "http://proxy.example.com:8080"
  https: "https://proxy.example.com:8080"

# Configurazione email per le notifiche
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  from: "your-email@gmail.com"
  to: "recipient@example.com"

# Configurazione dashboard
dashboard:
  title: "MIDA - Dashboard Missioni Internazionali"
  description: "Monitoraggio e analisi delle missioni internazionali italiane"
  theme: "light"
  port: 8501

# Configurazione report
report:
  template: "scripts/reports/templates/report_template.html"
  output_dir: "reports"
  retention_days: 30 